export const MUSCLE_GROUPS = [
  "Chest",
  "Back",
  "Shoulders",
  "Triceps",
  "Biceps",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Core",
  "Full Body",
];

export const EXERCISES_BY_MUSCLE = {
  Chest: [
    "Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Incline DB Press",
    "Flat DB Press",
    "DB Fly",
    "Cable Fly",
    "Push-Up",
    "Dips (Chest)",
  ],
  Back: [
    "Lat Pulldown",
    "Pull-Up",
    "Chin-Up",
    "Seated Row",
    "Bent Over Row",
    "Single Arm DB Row",
    "T-Bar Row",
    "Face Pull",
    "Deadlift",
  ],
  Shoulders: [
    "Overhead Press",
    "DB Shoulder Press",
    "Arnold Press",
    "Lateral Raise",
    "Front Raise",
    "Rear Delt Fly",
    "Cable Lateral Raise",
    "Upright Row",
    "Shrugs",
  ],
  Triceps: [
    "Tricep Pressdown",
    "Skull Crusher",
    "Overhead Tricep Extension",
    "Close Grip Bench Press",
    "Dips (Triceps)",
    "Cable Kickback",
  ],
  Biceps: [
    "Bicep Curl",
    "Hammer Curl",
    "Incline DB Curl",
    "Cable Curl",
    "Preacher Curl",
    "Concentration Curl",
    "EZ Bar Curl",
  ],
  Quads: [
    "Squat",
    "Front Squat",
    "Hack Squat",
    "Leg Press",
    "Leg Extension",
    "Bulgarian Split Squat",
    "Lunge",
    "Walking Lunge",
    "Step Up",
  ],
  Hamstrings: [
    "RDL",
    "Deadlift",
    "Leg Curl",
    "Seated Leg Curl",
    "Good Morning",
    "Nordic Curl",
    "Stiff Leg Deadlift",
  ],
  Glutes: [
    "Hip Thrust",
    "Glute Bridge",
    "Cable Kickback",
    "Sumo Deadlift",
    "Sumo Squat",
    "Clamshell",
    "Abductor Machine",
  ],
  Calves: ["Standing Calf Raise", "Seated Calf Raise", "Leg Press Calf Raise"],
  Core: [
    "Plank",
    "Ab Wheel",
    "Cable Crunch",
    "Hanging Leg Raise",
    "Sit-Up",
    "Russian Twist",
    "Dead Bug",
    "Pallof Press",
  ],
  "Full Body": ["Burpee", "Clean & Press", "Thruster", "Kettlebell Swing", "Turkish Get-Up"],
};

export const ALL_EXERCISES = Object.values(EXERCISES_BY_MUSCLE).flat();

export const DEFAULT_EXERCISES = [
  "Bench Press",
  "Incline DB Press",
  "Lat Pulldown",
  "Seated Row",
  "Squat",
  "RDL",
  "Hip Thrust",
  "Overhead Press",
  "Lateral Raise",
  "Bicep Curl",
  "Tricep Pressdown",
  "Bulgarian Split Squat",
];
